---
  - name: Playbook
    hosts: my-vm
    become: yes

    tasks:
      - name: Update apt cache
        apt: update_cache=yes cache_valid_time=3600

      - name: Upgrade all apt packages
        apt: upgrade=dist

      - name: Install dependencies
        apt:
          name: "{{ packages }}"
          state: present
          update_cache: yes
        vars:
          packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg-agent

      - name: Add an apt signing key for Docker
        apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present

      - name: Add apt repository for stable version
        apt_repository:
          repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
          state: present
      - name: Install Docker
        apt:
          name: "{{ packages }}"
          state: present
          update_cache: yes
        vars:
          packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io
      - name: ensure docker is started
        service:
          name: docker
          state: started
          enabled: yes

      - name: Install ignite depedencies
        apt:
          name: "{{ packages }}"
          state: present
          update_cache: yes
        vars:
          packages:
          - openssh-client
          - git
          - binutils
          - containerd
          
      - name: Download Ignite binary
        get_url:
          url: https://github.com/weaveworks/ignite/releases/download/v0.10.0/ignite-amd64
          dest: /usr/local/bin/ignite
          mode: 0755
      
      - name: Install Ignite binary
        get_url:
          url: https://github.com/weaveworks/ignite/releases/download/v0.10.0/ignite-amd64
          dest: /usr/local/bin/ignite
          mode: 0755
        get_url:
          url: https://github.com/weaveworks/ignite/releases/download/v0.10.0/ignited-amd64
          dest: /usr/local/bin/ignited
          mode: 0755

      - name: ensure ignite is installed
        shell: "which ignite"
        register: result
        ignore_errors: true
      - fail:
          msg: "ignite is not found! You need to install it first."
        when: result.rc != 0

      - name: Download firecracker binary
        get_url:
          url: https://github.com/firecracker-microvm/firecracker/releases/download/v1.0.0/firecracker-v1.0.0-x86_64.tgz
          dest: /home/user/firecracker.tgz
          mode: 0755

      - name: create directory for firecracker
        file:
          path: /home/user/firecracker
          state: directory
      - name: UNZIPPING firecracker binary
        unarchive:
          src : /home/user/firecracker.tgz
          dest: /home/user/firecracker
          remote_src: yes